# Generated by Django 4.2.7 on 2024-01-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_options_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('0', 'самовывоз'), ('1', 'Советский'), ('2', 'Володарский'), ('3', 'Фокинский'), ('4', 'Бежицкий')], default='0', max_length=20, verbose_name='Доставка'),
        ),
    ]
