# Generated by Django 4.2.7 on 2024-01-12 21:17

import django.core.validators
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, validators=[store.models.exam_mail], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('[+7][0-9]{10}', message='неправильный телефон')], verbose_name='Моб.телефон'),
        ),
    ]
