# Generated by Django 4.2.7 on 2024-01-12 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_email_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('[+7][0-9]{10}', message='Введите телефон в формате +7**********')], verbose_name='Моб.телефон'),
        ),
    ]
