# Generated by Django 4.2.7 on 2024-02-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма заказа (руб)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='ID транзакции'),
        ),
    ]
