# Generated by Django 4.2.7 on 2024-02-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_amount_alter_order_braintree_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='amount_rub',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма заказа (usd)'),
        ),
    ]
