# Generated by Django 4.2.7 on 2024-03-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_amount_order_amount_rub_order_amount_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Заказ доставлен/не доставлен'),
        ),
    ]
