# Generated by Django 4.2.7 on 2024-03-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доставлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
